wireguard:
    mullvad: ENC[AES256_GCM,data:Ijw/8Xu2sNrIGYBlvwFc7EX7QFHkTZ2yFDAFv8kVDugQw5JtJF60QR8N/YE=,iv:ioVIFXz0hlPU1TecFlO9JkVYixnn0uZDED5t1vnUdmo=,tag:TX+uq+bl7MnWbDjMwK2mEg==,type:str]
    umut: ENC[AES256_GCM,data:VbHS8HlpKekiBBoMG8fQAGLhYqxYwe3tAAlCYNQGfcshu5In4RM29k9/H8s=,iv:p7r6Z9SqrUEEKv5//d3G/NjaAySBIc4Xz/e7Eflrn+w=,tag:dgGlPCCLpPXUNWxLquZVTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zwgcw06rp5hdt7548kgh04x039fnz66rev33rny82dqtvjgs947qxnn0qt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuelE5R3F2Q2wrc3oxOG9k
            Nm45T0QwOUdWdlE4eHg1Ni9lTXA5OHI4SUJFClBROWpmZ3daT2orcklnZTNSaG1G
            RWNkV0N6c1l6LzQ1SUl0bld6cEJNQk0KLS0tIHhZZWYvWkhLVVpmY1FrREMxMkdU
            NkhaY3VXSWdqUzJKMlUyZFc0TjAvcVkK0WWWGrsh6K3HDm/u+mFTFcvwJtDuqL+r
            NqzT3gE5A8xH+ZRHqTzzW1QivOOcbdV/bWQ0OlLtqT4ceC0u+IGUfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T15:54:33Z"
    mac: ENC[AES256_GCM,data:SaJIlVMd8IjkgYJ2gECKu+jOIvFzYl9VfZexHZWThcvpj/Lysm9vokkAXPg7DEwc1oladXvqvgd4FEO8NHLcAkzBVmfqKQgVX/10EjuaSVm4oQ+FpGSTYRWwaHLczXOEjR2imMJ5UiAADhrGWq1sNlUBrSRPaxnsmGRd/VmUvrw=,iv:Kc2sYZ1Nei1UjKhpi7FEs0dfhiDXI7qceMIcqDem5uk=,tag:cgLxWCmvXiMzdMEdcn1g1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
